/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"

/*
 * Tasks to schedule
 */

void task1_handler(); //Task 1
void task2_handler(); //Task 2
void task3_handler(); //Task 3
void task4_handler(); //Task 4


/*
 * Function Declarations
 */
void init_systick_timer(uint32_t tick_hz);
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack);
void init_tasks_stack();
void enable_processor_faults();
uint32_t get_psp_value();
__attribute__((naked)) void switch_sp_to_psp();
void save_psp_value(uint32_t current_psp_val);
void update_next_task();
void task_delay(uint32_t tickCount);
void update_global_tick_count();
void unblock_tasks();

/*
 * Global Variables
 */
uint8_t current_task = 1; //Task1 running
uint32_t g_tick_count = 0;

typedef struct {
	uint32_t pspVal;
	uint32_t blockCount;
	uint8_t  currentState;
	void     (*task_handler) (void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];

int main(void)
{
	enable_processor_faults(); //Enables Mem Manage, Bus, and Usage Faults

	init_scheduler_stack(SCHED_STACK_START);

	init_tasks_stack();

	led_init_all(); //Intitalizes all LEDS

	init_systick_timer(TICK_HZ); //Generates SysTick Timer Exception

	switch_sp_to_psp(); //Switches from MSP to PSP

	task1_handler();

    /* Loop forever */
	for(;;);
}

void idle_task() {
	while(1);
}

void task1_handler() {
	while(1) {
		led_on(LED_GREEN); //Green LED
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}
}

void task2_handler() {
	while(1) {
		led_on(LED_ORANGE); //Orange LED
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
	}
}

void task3_handler() {
	while(1) {
		led_on(LED_BLUE); //Blue LED
		task_delay(250);
		led_off(LED_BLUE);
		task_delay(250);
	}
}

void task4_handler() {
	while(1) {
		led_on(LED_RED); //Red LED
		task_delay(125);
		led_off(LED_RED);
		task_delay(125);
	}
}

void init_systick_timer(uint32_t tick_hz) {
	uint32_t* pSRVR = (uint32_t*)  0xE000E014; //SysTick Reload Value Register
	uint32_t* pSCSR = (uint32_t*)  0xE000E010; //SysTick Control and Status Register
	uint32_t countVal = (SYSTICK_TIM_CLK / tick_hz) - 1; //Reload Value should be N-1 (Number of clock cycles - 1).

	//Clear value of SVR
	*pSRVR &= ~(0x00FFFFFFFF);

	//load value into SVR
	*pSRVR |= countVal;

	//Edit Settings
	*pSCSR |= (1 << 1); //Enables SysTick Exception Request
	*pSCSR |= (1 << 2); //Indicates that the clock source is the processor internal clock

	//Enable systick
	*pSCSR |= (1 << 0); //Enables the SysTick counter
}

/*
 * Must be a naked function to access MSP which is a special register
 */
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack) {
	__asm volatile("MSR MSP, %0": : "r" (sched_top_of_stack) : ); //Puts value of the top of the stack into MSP
	__asm volatile("BX LR"); //Return from function call
}



void init_tasks_stack() {

	user_tasks[0].currentState = TASK_READY_STATE;
	user_tasks[1].currentState = TASK_READY_STATE;
	user_tasks[2].currentState = TASK_READY_STATE;
	user_tasks[3].currentState = TASK_READY_STATE;
	user_tasks[4].currentState = TASK_READY_STATE;

	user_tasks[0].pspVal = IDLE_STACK_START;
	user_tasks[1].pspVal = T1_STACK_START;
	user_tasks[2].pspVal = T2_STACK_START;
	user_tasks[3].pspVal = T3_STACK_START;
	user_tasks[4].pspVal = T4_STACK_START;

	user_tasks[0].task_handler = task4_handler;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	uint32_t* pPSP;
	for (int i = 0; i < MAX_TASKS; i++) {
		pPSP = (uint32_t*) user_tasks[i].pspVal;

		pPSP --; //XPSR
		*pPSP = DUMMY_XPSR; //Should always be 0x01000000 to be in thumb set instructions

		pPSP --; //PC
		*pPSP = (uint32_t) user_tasks[i].task_handler;

		pPSP --; //LR
		*pPSP = 0xFFFFFFFD;

		//Sets the other reigsters to 0
		for (int j = 0; j < 13; j++) {
			pPSP --;
			*pPSP = 0;
		}

		user_tasks[i].pspVal = (uint32_t)pPSP; //Stores value of pPSP in global array
	}
}

/*
 * Enables memory manage, bus, and usage faults
 */
void enable_processor_faults() {
	uint32_t* pSHCSR = (uint32_t*) 0xE000ED24; //Address of System Handler Control and State Register

	*pSHCSR |= (1 << 16); //Memory Manage
	*pSHCSR |= (1 << 17); //Bus Fault
	*pSHCSR |= (1 << 18); //Usage Fault
}

uint32_t get_psp_value() {
	return user_tasks[current_task].pspVal;
}

void save_psp_value(uint32_t current_psp_val) {
	user_tasks[current_task].pspVal = current_psp_val;
}

void update_next_task() {

	int state = TASK_BLOCKED_STATE;

	for (int i = 0; i < (MAX_TASKS); i++) {
		current_task++;
		current_task = current_task % MAX_TASKS; //When it reaches Max Tasks it will start at beginning again
		state = user_tasks[current_task].currentState;
		if ( (state == TASK_READY_STATE) && (current_task != 0) ) {
			break;
		}
	}
	if (state != TASK_READY_STATE) {
		current_task = 0;
	}

}

__attribute__((naked)) void switch_sp_to_psp() {
	//1) Initialize PSP with Task1 Stack start address

	__asm volatile("PUSH {LR}"); //Pushes LR to the main to the stack
	__asm volatile("BL get_psp_value"); //Gets value of current PSP in R0
	__asm volatile("MSR PSP, R0"); //Initialize PSP
	__asm volatile("POP {LR}"); //Pops LR from the stack

	//2) Change SP to PSP with CONTROL Register
	__asm volatile ("MOV R0, #0x02"); //If Second bit of CONTROL Register is 1, then SP is now PSP
	__asm volatile ("MSR CONTROL, R0"); //Sets SP to PSP
	__asm volatile ("BX LR"); //Connects back to the main function
}

void schedule() {
	uint32_t* pICSR = (uint32_t*)  0xE000ED04; //ICSR address
	//pend the SV Exception
	*pICSR |= (1 << 28);
}

void task_delay(uint32_t tickCount) {
	//Disable the interrupt
	INTERRUPT_DISABLE();

	if (current_task) {
		user_tasks[current_task].blockCount = g_tick_count + tickCount;
		user_tasks[current_task].currentState = TASK_BLOCKED_STATE;
		schedule();
	}

	//Enable the interrupt
	INTERRUPT_ENABLE();
}

__attribute__((naked)) void PendSV_Handler() {
	/*
		 * Save the context of the current task
		 */

		//1) Get current running task's PSP value
		__asm volatile("MRS R0, PSP");

		//2) Using that PSP value store Stack frame 2 from R4 to R11
		__asm volatile("STMDB R0!, {R4-R11}");

		__asm volatile("PUSH {LR}"); //Save LR

		//3) Save the current value of PSP
		__asm volatile("BL save_psp_value");

		/*
		 * Retrieve context of next task
		 */

		//1) Find next task
		__asm volatile("BL update_next_task");

		//2) get its old PSP val
		__asm volatile("BL get_psp_value");

		//3) Using the old PSP val, retrieve R4 to R11
		__asm volatile("LDMIA R0, {R4-R11}");

		//4) update the PSP and exit handler
		__asm volatile("MSR PSP, R0");

		__asm volatile("POP {LR}");

		__asm volatile("BX LR");

}

void unblock_tasks() {
	for (int i = 0; i < MAX_TASKS; i++) {
		if (user_tasks[i].currentState != TASK_READY_STATE) {
			if (user_tasks[i].blockCount == g_tick_count) {
				user_tasks[i].currentState = TASK_READY_STATE;
			}
		}
	}
}

void update_global_tick_count() {
	g_tick_count++;
}

void SysTick_Handler() {

	uint32_t* pICSR = (uint32_t*)  0xE000ED04; //ICSR address

	update_global_tick_count();
	unblock_tasks();

	//pend the SV Exception
	*pICSR |= (1 << 28);

}

void HardFault_Handler() {
	//printf("HardFault Exception\n");
	while(1);
}

void MemManage_Handler() {
	//printf("MemManage Exception\n");
	while(1);
}

void BusFault_Handler() {
	//printf("BusFault Exception\n");
	while(1);
}
